// Firmware OTA update orchestration. Transport-agnostic: both BLE and Serial funnel through
// the same text-command channel (see src/ota.cpp / include/ota.h), so this file doesn't need
// to know which one is active - callers just pass the right sendChunk/chunkSize for it.

export type OtaManifestEntry = { size: number; md5: string; version: string; builtAt: string };
export type OtaManifest = { envs: Record<string, OtaManifestEntry> };

/** Simple numeric dot-separated compare (no semver lib needed for plain "x.y.z" strings). */
export function compareVersions(a: string, b: string): number {
  const pa = a.split('.').map((n) => parseInt(n, 10) || 0);
  const pb = b.split('.').map((n) => parseInt(n, 10) || 0);
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const diff = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (diff !== 0) return diff > 0 ? 1 : -1;
  }
  return 0;
}

/** Fetches the manifest generated by scripts/copy-firmware.mjs. Returns null on any failure
 * (not yet generated, network error, ...) so the UI can degrade to "can't check for updates". */
export async function fetchOtaManifest(): Promise<OtaManifest | null> {
  try {
    const res = await fetch('./ota/manifest.json', { cache: 'no-store' });
    if (!res.ok) return null;
    return (await res.json()) as OtaManifest;
  } catch {
    return null;
  }
}

export async function fetchOtaBinary(env: string): Promise<ArrayBuffer> {
  const res = await fetch(`./ota/${env}/firmware.bin`, { cache: 'no-store' });
  if (!res.ok) throw new Error(`Failed to fetch bundled firmware for "${env}" (HTTP ${res.status})`);
  return res.arrayBuffer();
}

/** Chunked to avoid blowing the call stack on String.fromCharCode(...bigArray). */
function bytesToBase64(bytes: Uint8Array): string {
  let binary = '';
  const step = 0x8000;
  for (let i = 0; i < bytes.length; i += step) {
    binary += String.fromCharCode(...bytes.subarray(i, i + step));
  }
  return btoa(binary);
}

/** Polls a live log array (via a getter, so it always sees the latest React state) for a line
 * matching `predicate`, starting from `sinceIndex`. Used to wait for the device's `[OTA] ...`
 * acks without needing a dedicated waiter mechanism threaded through both transport hooks. */
export function createLineWaiter(getLog: () => { line: string }[]) {
  return function waitForLine(predicate: (line: string) => boolean, sinceIndex: number, timeoutMs = 6000): Promise<string> {
    return new Promise((resolve, reject) => {
      const start = Date.now();
      const check = () => {
        const log = getLog();
        for (let i = sinceIndex; i < log.length; i++) {
          if (predicate(log[i].line)) {
            resolve(log[i].line);
            return;
          }
        }
        if (Date.now() - start > timeoutMs) {
          reject(new Error('Timed out waiting for a response from the device'));
          return;
        }
        setTimeout(check, 80);
      };
      check();
    });
  };
}

export type OtaProgress = { sentBytes: number; totalBytes: number };

export async function runOtaUpdate(opts: {
  bytes: ArrayBuffer;
  md5: string;
  version: string;
  chunkSize: number;
  sendCmd: (cmd: string) => Promise<void>;
  sendChunk: (cmd: string) => Promise<void>;
  waitForLine: (predicate: (line: string) => boolean, sinceIndex: number, timeoutMs?: number) => Promise<string>;
  logLength: () => number;
  onProgress?: (p: OtaProgress) => void;
}): Promise<void> {
  const { bytes, md5, version, chunkSize, sendCmd, sendChunk, waitForLine, logLength, onProgress } = opts;
  const data = new Uint8Array(bytes);

  let since = logLength();
  await sendCmd(`ota begin ${data.length} ${md5} ${version}`);
  const beginReply = await waitForLine((l) => l.startsWith('[OTA]'), since, 5000);
  if (!beginReply.toLowerCase().includes('ready')) {
    throw new Error(beginReply.replace(/^\[OTA\]\s*/, ''));
  }

  for (let offset = 0; offset < data.length; offset += chunkSize) {
    const slice = data.subarray(offset, offset + chunkSize);
    await sendChunk(`ota chunk ${bytesToBase64(slice)}`);
    onProgress?.({ sentBytes: Math.min(offset + slice.length, data.length), totalBytes: data.length });
  }

  since = logLength();
  await sendCmd('ota end');
  const endReply = await waitForLine((l) => l.startsWith('[OTA]'), since, 8000);
  if (!endReply.toLowerCase().includes('success')) {
    throw new Error(endReply.replace(/^\[OTA\]\s*/, ''));
  }
}
